/**
 * Content generation templates.
 * Each renderer takes a list of ArchiveEntry objects and produces a markdown string.
 * Templates are designed for storytelling, not corporate report writing.
 */
import type { ArchiveEntry } from '../core/schema.js'

// ─── Types ────────────────────────────────────────────────────────────────────

export type OutputFormat = 'blog' | 'case-study' | 'social' | 'thread'

// ─── Helpers ──────────────────────────────────────────────────────────────────

function footer(): string {
  return `\n---\n*Generated by [claude-archivist](https://github.com/apurvrdx1/claude-archivist-v1) on ${new Date().toISOString().slice(0, 10)}*`
}

function dateRange(entries: ArchiveEntry[]): string {
  if (!entries.length) return ''
  const dates = entries.map(e => e.session_date).sort()
  const first = dates[0]!
  const last = dates[dates.length - 1]!
  return first === last ? first : `${first} → ${last}`
}

function byImportance(entries: ArchiveEntry[]): ArchiveEntry[] {
  const order = { critical: 0, high: 1, medium: 2, low: 3 }
  return [...entries].sort((a, b) =>
    (order[a.importance as keyof typeof order] ?? 4) -
    (order[b.importance as keyof typeof order] ?? 4)
  )
}

function collectDecisions(entries: ArchiveEntry[]): string[] {
  return entries.flatMap(e => e.decisions?.decisions_made ?? []).filter(Boolean)
}

function collectFailures(entries: ArchiveEntry[]): string[] {
  return entries
    .map(e => e.failures?.errors_or_failures)
    .filter((f): f is string => Boolean(f))
}

function collectOutcomes(entries: ArchiveEntry[]): string[] {
  return entries
    .map(e => e.resolution?.outcome)
    .filter((o): o is string => Boolean(o))
}

// ─── Blog renderer ────────────────────────────────────────────────────────────

export function renderBlog(entries: ArchiveEntry[], projectName: string): string {
  const range = dateRange(entries)
  const lines: string[] = []

  lines.push(`# ${projectName}: Building in Public`)
  lines.push(``)
  if (range) lines.push(`*A documentary log — ${range}*`)
  lines.push(``)

  if (!entries.length) {
    lines.push(`*No entries recorded yet.*`)
    lines.push(footer())
    return lines.join('\n')
  }

  lines.push(`## The Story`)
  lines.push(``)

  for (const entry of entries) {
    lines.push(`### ${entry.objective}`)
    lines.push(``)
    lines.push(`*${entry.session_date} · ${entry.phase} · ${entry.interaction_type}*`)
    lines.push(``)

    // Voiceover is gold — show it first, verbatim
    if (entry.story?.voiceover_note) {
      lines.push(`> ${entry.story.voiceover_note}`)
      lines.push(``)
    }

    // What actually happened
    if (entry.interaction?.assistant_response_summary) {
      lines.push(entry.interaction.assistant_response_summary)
      lines.push(``)
    }

    // Preserve failures — don't sanitize
    if (entry.failures?.errors_or_failures) {
      lines.push(`**What went wrong:** ${entry.failures.errors_or_failures}`)
      lines.push(``)
    }

    // Tags
    const tags = entry.tags?.narrative_tags ?? []
    if (tags.length > 0) {
      lines.push(`*Tags: ${tags.join(', ')}*`)
      lines.push(``)
    }
  }

  // Decisions section
  const decisions = collectDecisions(entries)
  if (decisions.length > 0) {
    lines.push(`## Decisions Made`)
    lines.push(``)
    for (const d of decisions) lines.push(`- ${d}`)
    lines.push(``)
  }

  // What's next (last open loop)
  const lastLoop = [...entries]
    .reverse()
    .map(e => e.resolution?.next_open_loop)
    .find(Boolean)
  if (lastLoop) {
    lines.push(`## What's Next`)
    lines.push(``)
    lines.push(lastLoop)
    lines.push(``)
  }

  lines.push(footer())
  return lines.join('\n')
}

// ─── Case study renderer ──────────────────────────────────────────────────────

export function renderCaseStudy(entries: ArchiveEntry[], projectName: string): string {
  const range = dateRange(entries)
  const lines: string[] = []

  lines.push(`# ${projectName} — Case Study`)
  lines.push(``)
  if (range) lines.push(`*${range}*`)
  lines.push(``)

  if (!entries.length) {
    lines.push(`*No entries recorded yet.*`)
    lines.push(footer())
    return lines.join('\n')
  }

  // The Challenge — discovery/build entries, objectives
  lines.push(`## The Challenge`)
  lines.push(``)
  const challengeEntries = entries.filter(e => ['discovery', 'concepting', 'design'].includes(e.phase))
  const objectiveSample = challengeEntries.length > 0
    ? challengeEntries
    : entries.slice(0, Math.min(3, entries.length))
  for (const e of objectiveSample) {
    lines.push(`- **${e.objective}** *(${e.phase})*`)
  }
  lines.push(``)

  // Key Moments — high/critical entries
  const keyEntries = byImportance(entries).filter(e =>
    e.importance === 'critical' || e.importance === 'high'
  )
  if (keyEntries.length > 0) {
    lines.push(`## Key Moments`)
    lines.push(``)
    for (const entry of keyEntries) {
      lines.push(`### ${entry.objective}`)
      lines.push(``)
      if (entry.story?.voiceover_note) {
        lines.push(`> ${entry.story.voiceover_note}`)
        lines.push(``)
      }
      if (entry.interaction?.assistant_response_summary) {
        lines.push(entry.interaction.assistant_response_summary)
        lines.push(``)
      }
    }
  }

  // Decisions
  const decisions = collectDecisions(entries)
  if (decisions.length > 0) {
    lines.push(`## Decisions`)
    lines.push(``)
    for (const d of decisions) lines.push(`- ${d}`)
    lines.push(``)
  }

  // Failures & Recovery
  const failures = collectFailures(entries)
  if (failures.length > 0) {
    lines.push(`## Failures & Recovery`)
    lines.push(``)
    for (const f of failures) lines.push(`- ${f}`)
    lines.push(``)
  }

  // Outcome
  const outcomes = collectOutcomes(entries)
  if (outcomes.length > 0) {
    lines.push(`## Outcome`)
    lines.push(``)
    for (const o of outcomes) lines.push(o)
    lines.push(``)
  }

  lines.push(footer())
  return lines.join('\n')
}

// ─── Social renderer ──────────────────────────────────────────────────────────

export function renderSocial(entries: ArchiveEntry[], projectName: string): string {
  if (!entries.length) {
    return `Working on ${projectName}. More soon.${footer()}`
  }

  const lines: string[] = []

  // Lead with voiceover if a good one exists
  const voiceover = entries
    .map(e => e.story?.voiceover_note)
    .find((v): v is string => Boolean(v))

  if (voiceover) {
    lines.push(voiceover)
    lines.push(``)
  }

  // Most interesting moment by importance
  const star = byImportance(entries)[0]!
  if (!voiceover) {
    lines.push(`Working on ${projectName}: ${star.objective.toLowerCase()}.`)
    lines.push(``)
  }

  // Add a failure note if present — these are the most relatable posts
  const failure = entries.map(e => e.failures?.errors_or_failures).find(Boolean)
  if (failure) {
    lines.push(`Hit a snag: ${failure}`)
    lines.push(``)
  }

  // Outcome if resolved
  const outcome = entries.map(e => e.resolution?.outcome).find(Boolean)
  if (outcome) {
    lines.push(outcome)
    lines.push(``)
  }

  lines.push(`#buildinpublic`)

  return lines.join('\n')
}

// ─── Thread renderer ──────────────────────────────────────────────────────────

export function renderThread(entries: ArchiveEntry[], projectName: string): string {
  const posts: string[] = []

  // Post 1: intro
  posts.push(`1/ Working on **${projectName}**\n\nA thread on what it actually took to build this. 🧵`)

  if (!entries.length) {
    return posts.join('\n\n')
  }

  let counter = 2

  for (const entry of entries.slice(0, 8)) { // cap at 8 content posts
    const parts: string[] = []

    if (entry.story?.voiceover_note) {
      parts.push(entry.story.voiceover_note)
    } else {
      parts.push(entry.objective)
      if (entry.interaction?.assistant_response_summary) {
        const summary = entry.interaction.assistant_response_summary
        // Keep it short — first sentence only
        parts.push(summary.split('.')[0]! + '.')
      }
    }

    if (entry.failures?.errors_or_failures) {
      parts.push(`Snag: ${entry.failures.errors_or_failures}`)
    }

    const tags = entry.tags?.narrative_tags ?? []
    if (tags.includes('breakthrough') || tags.includes('pivot')) {
      parts.push(`(${tags.filter(t => ['breakthrough', 'pivot', 'shipped'].includes(t)).join(', ')})`)
    }

    posts.push(`${counter}/ ${parts.join('\n\n')}`)
    counter++
  }

  // Final post: what's next or shipped
  const lastLoop = [...entries]
    .reverse()
    .map(e => e.resolution?.next_open_loop)
    .find(Boolean)
  const shipped = entries.some(e => e.tags?.narrative_tags?.includes('shipped'))

  if (shipped) {
    posts.push(`${counter}/ Shipped. More to come.`)
  } else if (lastLoop) {
    posts.push(`${counter}/ Next up: ${lastLoop}`)
  }

  return posts.join('\n\n')
}
